@extends('backoffice.layouts.main')
@section('title')
    Icones
@endsection

@section('additionnal_css')
    <!-- Boxicons CSS -->
    <link rel="stylesheet" href="{{ asset('assets/new_client_side/css/boxicons.min.css') }}">

    <style>
        .demo-icon {
            display: flex;
            flex-direction: row;
            align-items: center;
            margin-bottom: 20px;
            padding: 10px;
            transition: all .2s;
        }

        .demo-icon:hover {
            background-color: #f4f5f8;
            border-radius: 3px;
        }

        .demo-icon .icon-preview {
            font-size: 1.8rem;
            margin-right: 10px;
            line-height: 1;
            color: #333439;
        }

        body[data-background-color="dark"] .demo-icon .icon-preview {
            color: #969696;
        }

        .demo-icon .icon-class {
            font-weight: 300;
            font-size: 13px;
            color: #777;
        }

        body[data-background-color="dark"] .demo-icon .icon-class {
            color: #a9a8a8;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <div class="page-inner">
            <div class="page-header">
                <h3 class="fw-bold mb-3">Icônes</h3>
            </div>
            <div class="row gy-5">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Font Awesome Icons</div>
                            <div class="card-category">Modern Font Icon from <a class="link"
                                    href="https://fontawesome.com">Font Awesome</a></div>
                        </div>
                        <div class="card-body">
                            <div id="row-demo-icon_1" class="row">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">BoxIcons</div>
                            <div class="card-category">Modern Font Icon from <a class="link"
                                    href="https://boxicons.com">BoxIcons</a></div>
                        </div>
                        <div class="card-body">
                            <div id="row-demo-icon_3" class="row">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Simple Line Icons</div>
                            <div class="card-category">Simple and Minimal Line Icons from <a class="link"
                                    href="https://github.com/thesabbir/simple-line-icons">Simple Line Icons</a></div>
                        </div>
                        <div class="card-body">
                            <div id="row-demo-icon_2" class="row">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('additionnal_js')
    <script>
        let iconClass = ['fas fa-address-book', 'fas fa-address-card', 'fas fa-adjust', 'fas fa-air-freshener',
            'fas fa-align-center', 'fas fa-align-justify', 'fas fa-align-left', 'fas fa-align-right',
            'fas fa-allergies', 'fas fa-ambulance', 'fas fa-american-sign-language-interpreting', 'fas fa-anchor',
            'fas fa-angle-double-down', 'fas fa-angle-double-left', 'fas fa-angle-double-right',
            'fas fa-angle-double-up', 'fas fa-angle-down', 'fas fa-angle-left', 'fas fa-angle-right', 'fas fa-angle-up',
            'fas fa-angry', 'fas fa-apple-alt', 'fas fa-archive', 'fas fa-archway', 'fas fa-arrow-alt-circle-down',
            'fas fa-arrow-alt-circle-left', 'fas fa-arrow-alt-circle-right', 'fas fa-arrow-alt-circle-up',
            'fas fa-arrow-circle-down', 'fas fa-arrow-circle-left', 'fas fa-arrow-circle-right',
            'fas fa-arrow-circle-up', 'fas fa-arrow-down', 'fas fa-arrow-left', 'fas fa-arrow-right', 'fas fa-arrow-up',
            'fas fa-arrows-alt', 'fas fa-arrows-alt-h', 'fas fa-arrows-alt-v', 'fas fa-assistive-listening-systems',
            'fas fa-asterisk', 'fas fa-at', 'fas fa-atlas', 'fas fa-atom', 'fas fa-audio-description', 'fas fa-award',
            'fas fa-backspace', 'fas fa-backward', 'fas fa-balance-scale', 'fas fa-ban', 'fas fa-band-aid',
            'fas fa-barcode', 'fas fa-bars', 'fas fa-baseball-ball', 'fas fa-basketball-ball', 'fas fa-bath',
            'fas fa-battery-empty', 'fas fa-battery-full', 'fas fa-battery-half', 'fas fa-battery-quarter',
            'fas fa-battery-three-quarters', 'fas fa-bed', 'fas fa-beer', 'fas fa-bell', 'fas fa-bell-slash',
            'fas fa-bezier-curve', 'fas fa-bicycle', 'fas fa-binoculars', 'fas fa-birthday-cake', 'fas fa-blender',
            'fas fa-blind', 'fas fa-bold', 'fas fa-bolt', 'fas fa-bomb', 'fas fa-bone', 'fas fa-bong', 'fas fa-book',
            'fas fa-book-open', 'fas fa-book-reader', 'fas fa-bookmark', 'fas fa-bowling-ball', 'fas fa-box',
            'fas fa-box-open', 'fas fa-boxes', 'fas fa-braille', 'fas fa-brain', 'fas fa-briefcase',
            'fas fa-briefcase-medical', 'fas fa-broadcast-tower', 'fas fa-broom', 'fas fa-brush', 'fas fa-bug',
            'fas fa-building', 'fas fa-bullhorn', 'fas fa-bullseye', 'fas fa-burn', 'fas fa-bus', 'fas fa-bus-alt',
            'fas fa-calculator', 'fas fa-calendar', 'fas fa-calendar-alt', 'fas fa-calendar-check',
            'fas fa-calendar-minus', 'fas fa-calendar-plus', 'fas fa-calendar-times', 'fas fa-camera',
            'fas fa-camera-retro', 'fas fa-cannabis', 'fas fa-capsules', 'fas fa-car', 'fas fa-car-alt',
            'fas fa-car-battery', 'fas fa-car-crash', 'fas fa-car-side', 'fas fa-caret-down', 'fas fa-caret-left',
            'fas fa-caret-right', 'fas fa-caret-square-down', 'fas fa-caret-square-left', 'fas fa-caret-square-right',
            'fas fa-caret-square-up', 'fas fa-caret-up', 'fas fa-cart-arrow-down', 'fas fa-cart-plus',
            'fas fa-certificate', 'fas fa-chalkboard', 'fas fa-chalkboard-teacher', 'fas fa-charging-station',
            'fas fa-chart-area', 'fas fa-chart-bar', 'fas fa-chart-line', 'fas fa-chart-pie', 'fas fa-check',
            'fas fa-check-circle', 'fas fa-check-double', 'fas fa-check-square', 'fas fa-chess', 'fas fa-chess-bishop',
            'fas fa-chess-board', 'fas fa-chess-king', 'fas fa-chess-knight', 'fas fa-chess-pawn', 'fas fa-chess-queen',
            'fas fa-chess-rook', 'fas fa-chevron-circle-down', 'fas fa-chevron-circle-left',
            'fas fa-chevron-circle-right', 'fas fa-chevron-circle-up', 'fas fa-chevron-down', 'fas fa-chevron-left',
            'fas fa-chevron-right', 'fas fa-chevron-up', 'fas fa-child', 'fas fa-church', 'fas fa-circle',
            'fas fa-circle-notch', 'fas fa-clipboard', 'fas fa-clipboard-check', 'fas fa-clipboard-list',
            'fas fa-clock', 'fas fa-clone', 'fas fa-closed-captioning', 'fas fa-cloud', 'fas fa-cloud-download-alt',
            'fas fa-cloud-upload-alt', 'fas fa-cocktail', 'fas fa-code', 'fas fa-code-branch', 'fas fa-coffee',
            'fas fa-cog', 'fas fa-cogs', 'fas fa-coins', 'fas fa-columns', 'fas fa-comment', 'fas fa-comment-alt',
            'fas fa-comment-dots', 'fas fa-comment-slash', 'fas fa-comments', 'fas fa-compact-disc', 'fas fa-compass',
            'fas fa-compress', 'fas fa-concierge-bell', 'fas fa-cookie', 'fas fa-cookie-bite', 'fas fa-copy',
            'fas fa-copyright', 'fas fa-couch', 'fas fa-credit-card', 'fas fa-crop', 'fas fa-crop-alt',
            'fas fa-crosshairs', 'fas fa-crow', 'fas fa-crown', 'fas fa-cube', 'fas fa-cubes', 'fas fa-cut',
            'fas fa-database', 'fas fa-deaf', 'fas fa-desktop', 'fas fa-diagnoses', 'fas fa-dice', 'fas fa-dice-five',
            'fas fa-dice-four', 'fas fa-dice-one', 'fas fa-dice-six', 'fas fa-dice-three', 'fas fa-dice-two',
            'fas fa-digital-tachograph', 'fas fa-directions', 'fas fa-divide', 'fas fa-dizzy', 'fas fa-dna',
            'fas fa-dollar-sign', 'fas fa-dolly', 'fas fa-dolly-flatbed', 'fas fa-donate', 'fas fa-door-closed',
            'fas fa-door-open', 'fas fa-dot-circle', 'fas fa-dove', 'fas fa-download', 'fas fa-drafting-compass',
            'fas fa-draw-polygon', 'fas fa-drum', 'fas fa-drum-steelpan', 'fas fa-dumbbell', 'fas fa-edit',
            'fas fa-eject', 'fas fa-ellipsis-h', 'fas fa-ellipsis-v', 'fas fa-envelope', 'fas fa-envelope-open',
            'fas fa-envelope-square', 'fas fa-equals', 'fas fa-eraser', 'fas fa-euro-sign', 'fas fa-exchange-alt',
            'fas fa-exclamation', 'fas fa-exclamation-circle', 'fas fa-exclamation-triangle', 'fas fa-expand',
            'fas fa-expand-arrows-alt', 'fas fa-external-link-alt', 'fas fa-external-link-square-alt', 'fas fa-eye',
            'fas fa-eye-dropper', 'fas fa-eye-slash', 'fas fa-fast-backward', 'fas fa-fast-forward', 'fas fa-fax',
            'fas fa-feather', 'fas fa-feather-alt', 'fas fa-female', 'fas fa-fighter-jet', 'fas fa-file',
            'fas fa-file-alt', 'fas fa-file-archive', 'fas fa-file-audio', 'fas fa-file-code', 'fas fa-file-contract',
            'fas fa-file-download', 'fas fa-file-excel', 'fas fa-file-export', 'fas fa-file-image',
            'fas fa-file-import', 'fas fa-file-invoice', 'fas fa-file-invoice-dollar', 'fas fa-file-medical',
            'fas fa-file-medical-alt', 'fas fa-file-pdf', 'fas fa-file-powerpoint', 'fas fa-file-prescription',
            'fas fa-file-signature', 'fas fa-file-upload', 'fas fa-file-video', 'fas fa-file-word', 'fas fa-fill',
            'fas fa-fill-drip', 'fas fa-film', 'fas fa-filter', 'fas fa-fingerprint', 'fas fa-fire',
            'fas fa-fire-extinguisher', 'fas fa-first-aid', 'fas fa-fish', 'fas fa-flag', 'fas fa-flag-checkered',
            'fas fa-flask', 'fas fa-flushed', 'fas fa-folder', 'fas fa-folder-open', 'fas fa-font',
            'fas fa-football-ball', 'fas fa-forward', 'fas fa-frog', 'fas fa-frown', 'fas fa-frown-open',
            'fas fa-futbol', 'fas fa-gamepad', 'fas fa-gas-pump', 'fas fa-gavel', 'fas fa-gem', 'fas fa-genderless',
            'fas fa-gift', 'fas fa-glass-martini', 'fas fa-glass-martini-alt', 'fas fa-glasses', 'fas fa-globe',
            'fas fa-globe-africa', 'fas fa-globe-americas', 'fas fa-globe-asia', 'fas fa-golf-ball',
            'fas fa-graduation-cap', 'fas fa-greater-than', 'fas fa-greater-than-equal', 'fas fa-grimace',
            'fas fa-grin', 'fas fa-grin-alt', 'fas fa-grin-beam', 'fas fa-grin-beam-sweat', 'fas fa-grin-hearts',
            'fas fa-grin-squint', 'fas fa-grin-squint-tears', 'fas fa-grin-stars', 'fas fa-grin-tears',
            'fas fa-grin-tongue', 'fas fa-grin-tongue-squint', 'fas fa-grin-tongue-wink', 'fas fa-grin-wink',
            'fas fa-grip-horizontal', 'fas fa-grip-vertical', 'fas fa-h-square', 'fas fa-hand-holding',
            'fas fa-hand-holding-heart', 'fas fa-hand-holding-usd', 'fas fa-hand-lizard', 'fas fa-hand-paper',
            'fas fa-hand-peace', 'fas fa-hand-point-down', 'fas fa-hand-point-left', 'fas fa-hand-point-right',
            'fas fa-hand-point-up', 'fas fa-hand-pointer', 'fas fa-hand-rock', 'fas fa-hand-scissors',
            'fas fa-hand-spock', 'fas fa-hands', 'fas fa-hands-helping', 'fas fa-handshake', 'fas fa-hashtag',
            'fas fa-hdd', 'fas fa-heading', 'fas fa-headphones', 'fas fa-headphones-alt', 'fas fa-headset',
            'fas fa-heart', 'fas fa-heartbeat', 'fas fa-helicopter', 'fas fa-highlighter', 'fas fa-history',
            'fas fa-hockey-puck', 'fas fa-home', 'fas fa-hospital', 'fas fa-hospital-alt', 'fas fa-hospital-symbol',
            'fas fa-hot-tub', 'fas fa-hotel', 'fas fa-hourglass', 'fas fa-hourglass-end', 'fas fa-hourglass-half',
            'fas fa-hourglass-start', 'fas fa-i-cursor', 'fas fa-id-badge', 'fas fa-id-card', 'fas fa-id-card-alt',
            'fas fa-image', 'fas fa-images', 'fas fa-inbox', 'fas fa-indent', 'fas fa-industry', 'fas fa-infinity',
            'fas fa-info', 'fas fa-info-circle', 'fas fa-italic', 'fas fa-joint', 'fas fa-key', 'fas fa-keyboard',
            'fas fa-kiss', 'fas fa-kiss-beam', 'fas fa-kiss-wink-heart', 'fas fa-kiwi-bird', 'fas fa-language',
            'fas fa-laptop', 'fas fa-laptop-code', 'fas fa-laugh', 'fas fa-laugh-beam', 'fas fa-laugh-squint',
            'fas fa-laugh-wink', 'fas fa-layer-group', 'fas fa-leaf', 'fas fa-lemon', 'fas fa-less-than',
            'fas fa-less-than-equal', 'fas fa-level-down-alt', 'fas fa-level-up-alt', 'fas fa-life-ring',
            'fas fa-lightbulb', 'fas fa-link', 'fas fa-lira-sign', 'fas fa-list', 'fas fa-list-alt', 'fas fa-list-ol',
            'fas fa-list-ul', 'fas fa-location-arrow', 'fas fa-lock', 'fas fa-lock-open', 'fas fa-long-arrow-alt-down',
            'fas fa-long-arrow-alt-left', 'fas fa-long-arrow-alt-right', 'fas fa-long-arrow-alt-up',
            'fas fa-low-vision', 'fas fa-luggage-cart', 'fas fa-magic', 'fas fa-magnet', 'fas fa-male', 'fas fa-map',
            'fas fa-map-marked', 'fas fa-map-marked-alt', 'fas fa-map-marker', 'fas fa-map-marker-alt',
            'fas fa-map-pin', 'fas fa-map-signs', 'fas fa-marker', 'fas fa-mars', 'fas fa-mars-double',
            'fas fa-mars-stroke', 'fas fa-mars-stroke-h', 'fas fa-mars-stroke-v', 'fas fa-medal', 'fas fa-medkit',
            'fas fa-meh', 'fas fa-meh-blank', 'fas fa-meh-rolling-eyes', 'fas fa-memory', 'fas fa-mercury',
            'fas fa-microchip', 'fas fa-microphone', 'fas fa-microphone-alt', 'fas fa-microphone-alt-slash',
            'fas fa-microphone-slash', 'fas fa-microscope', 'fas fa-minus', 'fas fa-minus-circle',
            'fas fa-minus-square', 'fas fa-mobile', 'fas fa-mobile-alt', 'fas fa-money-bill', 'fas fa-money-bill-alt',
            'fas fa-money-bill-wave', 'fas fa-money-bill-wave-alt', 'fas fa-money-check', 'fas fa-money-check-alt',
            'fas fa-monument', 'fas fa-moon', 'fas fa-mortar-pestle', 'fas fa-motorcycle', 'fas fa-mouse-pointer',
            'fas fa-music', 'fas fa-neuter', 'fas fa-newspaper', 'fas fa-not-equal', 'fas fa-notes-medical',
            'fas fa-object-group', 'fas fa-object-ungroup', 'fas fa-oil-can', 'fas fa-outdent', 'fas fa-paint-brush',
            'fas fa-paint-roller', 'fas fa-palette', 'fas fa-pallet', 'fas fa-paper-plane', 'fas fa-paperclip',
            'fas fa-parachute-box', 'fas fa-paragraph', 'fas fa-parking', 'fas fa-passport', 'fas fa-paste',
            'fas fa-pause', 'fas fa-pause-circle', 'fas fa-paw', 'fas fa-pen', 'fas fa-pen-alt', 'fas fa-pen-fancy',
            'fas fa-pen-nib', 'fas fa-pen-square', 'fas fa-pencil-alt', 'fas fa-pencil-ruler', 'fas fa-people-carry',
            'fas fa-percent', 'fas fa-percentage', 'fas fa-phone', 'fas fa-phone-slash', 'fas fa-phone-square',
            'fas fa-phone-volume', 'fas fa-piggy-bank', 'fas fa-pills', 'fas fa-plane', 'fas fa-plane-arrival',
            'fas fa-plane-departure', 'fas fa-play', 'fas fa-play-circle', 'fas fa-plug', 'fas fa-plus',
            'fas fa-plus-circle', 'fas fa-plus-square', 'fas fa-podcast', 'fas fa-poo', 'fas fa-poop',
            'fas fa-portrait', 'fas fa-pound-sign', 'fas fa-power-off', 'fas fa-prescription',
            'fas fa-prescription-bottle', 'fas fa-prescription-bottle-alt', 'fas fa-print', 'fas fa-procedures',
            'fas fa-project-diagram', 'fas fa-puzzle-piece', 'fas fa-qrcode', 'fas fa-question',
            'fas fa-question-circle', 'fas fa-quidditch', 'fas fa-quote-left', 'fas fa-quote-right', 'fas fa-random',
            'fas fa-receipt', 'fas fa-recycle', 'fas fa-redo', 'fas fa-redo-alt', 'fas fa-registered', 'fas fa-reply',
            'fas fa-reply-all', 'fas fa-retweet', 'fas fa-ribbon', 'fas fa-road', 'fas fa-robot', 'fas fa-rocket',
            'fas fa-route', 'fas fa-rss', 'fas fa-rss-square', 'fas fa-ruble-sign', 'fas fa-ruler',
            'fas fa-ruler-combined', 'fas fa-ruler-horizontal', 'fas fa-ruler-vertical', 'fas fa-rupee-sign',
            'fas fa-sad-cry', 'fas fa-sad-tear', 'fas fa-save', 'fas fa-school', 'fas fa-screwdriver', 'fas fa-search',
            'fas fa-search-minus', 'fas fa-search-plus', 'fas fa-seedling', 'fas fa-server', 'fas fa-shapes',
            'fas fa-share', 'fas fa-share-alt', 'fas fa-share-alt-square', 'fas fa-share-square', 'fas fa-shekel-sign',
            'fas fa-shield-alt', 'fas fa-ship', 'fas fa-shipping-fast', 'fas fa-shoe-prints', 'fas fa-shopping-bag',
            'fas fa-shopping-basket', 'fas fa-shopping-cart', 'fas fa-shower', 'fas fa-shuttle-van', 'fas fa-sign',
            'fas fa-sign-in-alt', 'fas fa-sign-language', 'fas fa-sign-out-alt', 'fas fa-signal', 'fas fa-signature',
            'fas fa-sitemap', 'fas fa-skull', 'fas fa-sliders-h', 'fas fa-smile', 'fas fa-smile-beam',
            'fas fa-smile-wink', 'fas fa-smoking', 'fas fa-smoking-ban', 'fas fa-snowflake', 'fas fa-solar-panel',
            'fas fa-sort', 'fas fa-sort-alpha-down', 'fas fa-sort-alpha-up', 'fas fa-sort-amount-down',
            'fas fa-sort-amount-up', 'fas fa-sort-down', 'fas fa-sort-numeric-down', 'fas fa-sort-numeric-up',
            'fas fa-sort-up', 'fas fa-spa', 'fas fa-space-shuttle', 'fas fa-spinner', 'fas fa-splotch',
            'fas fa-spray-can', 'fas fa-square', 'fas fa-square-full', 'fas fa-stamp', 'fas fa-star',
            'fas fa-star-half', 'fas fa-star-half-alt', 'fas fa-star-of-life', 'fas fa-step-backward',
            'fas fa-step-forward', 'fas fa-stethoscope', 'fas fa-sticky-note', 'fas fa-stop', 'fas fa-stop-circle',
            'fas fa-stopwatch', 'fas fa-store', 'fas fa-store-alt', 'fas fa-stream', 'fas fa-street-view',
            'fas fa-strikethrough', 'fas fa-stroopwafel', 'fas fa-subscript', 'fas fa-subway', 'fas fa-suitcase',
            'fas fa-suitcase-rolling', 'fas fa-sun', 'fas fa-superscript', 'fas fa-surprise', 'fas fa-swatchbook',
            'fas fa-swimmer', 'fas fa-swimming-pool', 'fas fa-sync', 'fas fa-sync-alt', 'fas fa-syringe',
            'fas fa-table', 'fas fa-table-tennis', 'fas fa-tablet', 'fas fa-tablet-alt', 'fas fa-tablets',
            'fas fa-tachometer-alt', 'fas fa-tag', 'fas fa-tags', 'fas fa-tape', 'fas fa-tasks', 'fas fa-taxi',
            'fas fa-teeth', 'fas fa-teeth-open', 'fas fa-terminal', 'fas fa-text-height', 'fas fa-text-width',
            'fas fa-th', 'fas fa-th-large', 'fas fa-th-list', 'fas fa-theater-masks', 'fas fa-thermometer',
            'fas fa-thermometer-empty', 'fas fa-thermometer-full', 'fas fa-thermometer-half',
            'fas fa-thermometer-quarter', 'fas fa-thermometer-three-quarters', 'fas fa-thumbs-down', 'fas fa-thumbs-up',
            'fas fa-thumbtack', 'fas fa-ticket-alt', 'fas fa-times', 'fas fa-times-circle', 'fas fa-tint',
            'fas fa-tint-slash', 'fas fa-tired', 'fas fa-toggle-off', 'fas fa-toggle-on', 'fas fa-toolbox',
            'fas fa-tooth', 'fas fa-trademark', 'fas fa-traffic-light', 'fas fa-train', 'fas fa-transgender',
            'fas fa-transgender-alt', 'fas fa-trash', 'fas fa-trash-alt', 'fas fa-tree', 'fas fa-trophy',
            'fas fa-truck', 'fas fa-truck-loading', 'fas fa-truck-monster', 'fas fa-truck-moving',
            'fas fa-truck-pickup', 'fas fa-tshirt', 'fas fa-tty', 'fas fa-tv', 'fas fa-umbrella',
            'fas fa-umbrella-beach', 'fas fa-underline', 'fas fa-undo', 'fas fa-undo-alt', 'fas fa-universal-access',
            'fas fa-university', 'fas fa-unlink', 'fas fa-unlock', 'fas fa-unlock-alt', 'fas fa-upload', 'fas fa-user',
            'fas fa-user-alt', 'fas fa-user-alt-slash', 'fas fa-user-astronaut', 'fas fa-user-check',
            'fas fa-user-circle', 'fas fa-user-clock', 'fas fa-user-cog', 'fas fa-user-edit', 'fas fa-user-friends',
            'fas fa-user-graduate', 'fas fa-user-lock', 'fas fa-user-md', 'fas fa-user-minus', 'fas fa-user-ninja',
            'fas fa-user-plus', 'fas fa-user-secret', 'fas fa-user-shield', 'fas fa-user-slash', 'fas fa-user-tag',
            'fas fa-user-tie', 'fas fa-user-times', 'fas fa-users', 'fas fa-users-cog', 'fas fa-utensil-spoon',
            'fas fa-utensils', 'fas fa-vector-square', 'fas fa-venus', 'fas fa-venus-double', 'fas fa-venus-mars',
            'fas fa-vial', 'fas fa-vials', 'fas fa-video', 'fas fa-video-slash', 'fas fa-volleyball-ball',
            'fas fa-volume-down', 'fas fa-volume-off', 'fas fa-volume-up', 'fas fa-walking', 'fas fa-wallet',
            'fas fa-warehouse', 'fas fa-weight', 'fas fa-weight-hanging', 'fas fa-wheelchair', 'fas fa-wifi',
            'fas fa-window-close', 'fas fa-window-maximize', 'fas fa-window-minimize', 'fas fa-window-restore',
            'fas fa-wine-glass', 'fas fa-wine-glass-alt', 'fas fa-won-sign', 'fas fa-wrench', 'fas fa-x-ray',
            'fas fa-yen-sign', 'far fa-address-book', 'far fa-address-card', 'far fa-angry',
            'far fa-arrow-alt-circle-down', 'far fa-arrow-alt-circle-left', 'far fa-arrow-alt-circle-right',
            'far fa-arrow-alt-circle-up', 'far fa-bell', 'far fa-bell-slash', 'far fa-bookmark', 'far fa-building',
            'far fa-calendar', 'far fa-calendar-alt', 'far fa-calendar-check', 'far fa-calendar-minus',
            'far fa-calendar-plus', 'far fa-calendar-times', 'far fa-caret-square-down', 'far fa-caret-square-left',
            'far fa-caret-square-right', 'far fa-caret-square-up', 'far fa-chart-bar', 'far fa-check-circle',
            'far fa-check-square', 'far fa-circle', 'far fa-clipboard', 'far fa-clock', 'far fa-clone',
            'far fa-closed-captioning', 'far fa-comment', 'far fa-comment-alt', 'far fa-comment-dots',
            'far fa-comments', 'far fa-compass', 'far fa-copy', 'far fa-copyright', 'far fa-credit-card',
            'far fa-dizzy', 'far fa-dot-circle', 'far fa-edit', 'far fa-envelope', 'far fa-envelope-open', 'far fa-eye',
            'far fa-eye-slash', 'far fa-file', 'far fa-file-alt', 'far fa-file-archive', 'far fa-file-audio',
            'far fa-file-code', 'far fa-file-excel', 'far fa-file-image', 'far fa-file-pdf', 'far fa-file-powerpoint',
            'far fa-file-video', 'far fa-file-word', 'far fa-flag', 'far fa-flushed', 'far fa-folder',
            'far fa-folder-open', 'far fa-frown', 'far fa-frown-open', 'far fa-futbol', 'far fa-gem', 'far fa-grimace',
            'far fa-grin', 'far fa-grin-alt', 'far fa-grin-beam', 'far fa-grin-beam-sweat', 'far fa-grin-hearts',
            'far fa-grin-squint', 'far fa-grin-squint-tears', 'far fa-grin-stars', 'far fa-grin-tears',
            'far fa-grin-tongue', 'far fa-grin-tongue-squint', 'far fa-grin-tongue-wink', 'far fa-grin-wink',
            'far fa-hand-lizard', 'far fa-hand-paper', 'far fa-hand-peace', 'far fa-hand-point-down',
            'far fa-hand-point-left', 'far fa-hand-point-right', 'far fa-hand-point-up', 'far fa-hand-pointer',
            'far fa-hand-rock', 'far fa-hand-scissors', 'far fa-hand-spock', 'far fa-handshake', 'far fa-hdd',
            'far fa-heart', 'far fa-hospital', 'far fa-hourglass', 'far fa-id-badge', 'far fa-id-card', 'far fa-image',
            'far fa-images', 'far fa-keyboard', 'far fa-kiss', 'far fa-kiss-beam', 'far fa-kiss-wink-heart',
            'far fa-laugh', 'far fa-laugh-beam', 'far fa-laugh-squint', 'far fa-laugh-wink', 'far fa-lemon',
            'far fa-life-ring', 'far fa-lightbulb', 'far fa-list-alt', 'far fa-map', 'far fa-meh', 'far fa-meh-blank',
            'far fa-meh-rolling-eyes', 'far fa-minus-square', 'far fa-money-bill-alt', 'far fa-moon',
            'far fa-newspaper', 'far fa-object-group', 'far fa-object-ungroup', 'far fa-paper-plane',
            'far fa-pause-circle', 'far fa-play-circle', 'far fa-plus-square', 'far fa-question-circle',
            'far fa-registered', 'far fa-sad-cry', 'far fa-sad-tear', 'far fa-save', 'far fa-share-square',
            'far fa-smile', 'far fa-smile-beam', 'far fa-smile-wink', 'far fa-snowflake', 'far fa-square',
            'far fa-star', 'far fa-star-half', 'far fa-sticky-note', 'far fa-stop-circle', 'far fa-sun',
            'far fa-surprise', 'far fa-thumbs-down', 'far fa-thumbs-up', 'far fa-times-circle', 'far fa-tired',
            'far fa-trash-alt', 'far fa-user', 'far fa-user-circle', 'far fa-window-close', 'far fa-window-maximize',
            'far fa-window-minimize', 'far fa-window-restore', 'fab fa-500px', 'fab fa-accessible-icon',
            'fab fa-accusoft', 'fab fa-adn', 'fab fa-adversal', 'fab fa-affiliatetheme', 'fab fa-algolia',
            'fab fa-amazon', 'fab fa-amazon-pay', 'fab fa-amilia', 'fab fa-android', 'fab fa-angellist',
            'fab fa-angrycreative', 'fab fa-angular', 'fab fa-app-store', 'fab fa-app-store-ios', 'fab fa-apper',
            'fab fa-apple', 'fab fa-apple-pay', 'fab fa-asymmetrik', 'fab fa-audible', 'fab fa-autoprefixer',
            'fab fa-avianex', 'fab fa-aviato', 'fab fa-aws', 'fab fa-bandcamp', 'fab fa-behance',
            'fab fa-behance-square', 'fab fa-bimobject', 'fab fa-bitbucket', 'fab fa-bitcoin', 'fab fa-bity',
            'fab fa-black-tie', 'fab fa-blackberry', 'fab fa-blogger', 'fab fa-blogger-b', 'fab fa-bluetooth',
            'fab fa-bluetooth-b', 'fab fa-btc', 'fab fa-buromobelexperte', 'fab fa-buysellads', 'fab fa-cc-amazon-pay',
            'fab fa-cc-amex', 'fab fa-cc-apple-pay', 'fab fa-cc-diners-club', 'fab fa-cc-discover', 'fab fa-cc-jcb',
            'fab fa-cc-mastercard', 'fab fa-cc-paypal', 'fab fa-cc-stripe', 'fab fa-cc-visa', 'fab fa-centercode',
            'fab fa-chrome', 'fab fa-cloudscale', 'fab fa-cloudsmith', 'fab fa-cloudversify', 'fab fa-codepen',
            'fab fa-codiepie', 'fab fa-connectdevelop', 'fab fa-contao', 'fab fa-cpanel', 'fab fa-creative-commons',
            'fab fa-creative-commons-by', 'fab fa-creative-commons-nc', 'fab fa-creative-commons-nc-eu',
            'fab fa-creative-commons-nc-jp', 'fab fa-creative-commons-nd', 'fab fa-creative-commons-pd',
            'fab fa-creative-commons-pd-alt', 'fab fa-creative-commons-remix', 'fab fa-creative-commons-sa',
            'fab fa-creative-commons-sampling', 'fab fa-creative-commons-sampling-plus',
            'fab fa-creative-commons-share', 'fab fa-css3', 'fab fa-css3-alt', 'fab fa-cuttlefish', 'fab fa-d-and-d',
            'fab fa-dashcube', 'fab fa-delicious', 'fab fa-deploydog', 'fab fa-deskpro', 'fab fa-deviantart',
            'fab fa-digg', 'fab fa-digital-ocean', 'fab fa-discord', 'fab fa-discourse', 'fab fa-dochub',
            'fab fa-docker', 'fab fa-draft2digital', 'fab fa-dribbble', 'fab fa-dribbble-square', 'fab fa-dropbox',
            'fab fa-drupal', 'fab fa-dyalog', 'fab fa-earlybirds', 'fab fa-ebay', 'fab fa-edge', 'fab fa-elementor',
            'fab fa-ello', 'fab fa-ember', 'fab fa-empire', 'fab fa-envira', 'fab fa-erlang', 'fab fa-ethereum',
            'fab fa-etsy', 'fab fa-expeditedssl', 'fab fa-facebook', 'fab fa-facebook-f', 'fab fa-facebook-messenger',
            'fab fa-facebook-square', 'fab fa-firefox', 'fab fa-first-order', 'fab fa-first-order-alt',
            'fab fa-firstdraft', 'fab fa-flickr', 'fab fa-flipboard', 'fab fa-fly', 'fab fa-font-awesome',
            'fab fa-font-awesome-alt', 'fab fa-font-awesome-flag', 'fab fa-fonticons', 'fab fa-fonticons-fi',
            'fab fa-fort-awesome', 'fab fa-fort-awesome-alt', 'fab fa-forumbee', 'fab fa-foursquare',
            'fab fa-free-code-camp', 'fab fa-freebsd', 'fab fa-fulcrum', 'fab fa-galactic-republic',
            'fab fa-galactic-senate', 'fab fa-get-pocket', 'fab fa-gg', 'fab fa-gg-circle', 'fab fa-git',
            'fab fa-git-square', 'fab fa-github', 'fab fa-github-alt', 'fab fa-github-square', 'fab fa-gitkraken',
            'fab fa-gitlab', 'fab fa-gitter', 'fab fa-glide', 'fab fa-glide-g', 'fab fa-gofore', 'fab fa-goodreads',
            'fab fa-goodreads-g', 'fab fa-google', 'fab fa-google-drive', 'fab fa-google-play', 'fab fa-google-plus',
            'fab fa-google-plus-g', 'fab fa-google-plus-square', 'fab fa-google-wallet', 'fab fa-gratipay',
            'fab fa-grav', 'fab fa-gripfire', 'fab fa-grunt', 'fab fa-gulp', 'fab fa-hacker-news',
            'fab fa-hacker-news-square', 'fab fa-hackerrank', 'fab fa-hips', 'fab fa-hire-a-helper', 'fab fa-hooli',
            'fab fa-hornbill', 'fab fa-hotjar', 'fab fa-houzz', 'fab fa-html5', 'fab fa-hubspot', 'fab fa-imdb',
            'fab fa-instagram', 'fab fa-internet-explorer', 'fab fa-ioxhost', 'fab fa-itunes', 'fab fa-itunes-note',
            'fab fa-java', 'fab fa-jedi-order', 'fab fa-jenkins', 'fab fa-joget', 'fab fa-joomla', 'fab fa-js',
            'fab fa-js-square', 'fab fa-jsfiddle', 'fab fa-kaggle', 'fab fa-keybase', 'fab fa-keycdn',
            'fab fa-kickstarter', 'fab fa-kickstarter-k', 'fab fa-korvue', 'fab fa-laravel', 'fab fa-lastfm',
            'fab fa-lastfm-square', 'fab fa-leanpub', 'fab fa-less', 'fab fa-line', 'fab fa-linkedin',
            'fab fa-linkedin-in', 'fab fa-linode', 'fab fa-linux', 'fab fa-lyft', 'fab fa-magento', 'fab fa-mailchimp',
            'fab fa-mandalorian', 'fab fa-markdown', 'fab fa-mastodon', 'fab fa-maxcdn', 'fab fa-medapps',
            'fab fa-medium', 'fab fa-medium-m', 'fab fa-medrt', 'fab fa-meetup', 'fab fa-megaport', 'fab fa-microsoft',
            'fab fa-mix', 'fab fa-mixcloud', 'fab fa-mizuni', 'fab fa-modx', 'fab fa-monero', 'fab fa-napster',
            'fab fa-neos', 'fab fa-nimblr', 'fab fa-nintendo-switch', 'fab fa-node', 'fab fa-node-js', 'fab fa-npm',
            'fab fa-ns8', 'fab fa-nutritionix', 'fab fa-odnoklassniki', 'fab fa-odnoklassniki-square',
            'fab fa-old-republic', 'fab fa-opencart', 'fab fa-openid', 'fab fa-opera', 'fab fa-optin-monster',
            'fab fa-osi', 'fab fa-page4', 'fab fa-pagelines', 'fab fa-palfed', 'fab fa-patreon', 'fab fa-paypal',
            'fab fa-periscope', 'fab fa-phabricator', 'fab fa-phoenix-framework', 'fab fa-phoenix-squadron',
            'fab fa-php', 'fab fa-pied-piper', 'fab fa-pied-piper-alt', 'fab fa-pied-piper-hat', 'fab fa-pied-piper-pp',
            'fab fa-pinterest', 'fab fa-pinterest-p', 'fab fa-pinterest-square', 'fab fa-playstation',
            'fab fa-product-hunt', 'fab fa-pushed', 'fab fa-python', 'fab fa-qq', 'fab fa-quinscape', 'fab fa-quora',
            'fab fa-r-project', 'fab fa-ravelry', 'fab fa-react', 'fab fa-readme', 'fab fa-rebel', 'fab fa-red-river',
            'fab fa-reddit', 'fab fa-reddit-alien', 'fab fa-reddit-square', 'fab fa-rendact', 'fab fa-renren',
            'fab fa-replyd', 'fab fa-researchgate', 'fab fa-resolving', 'fab fa-rev', 'fab fa-rocketchat',
            'fab fa-rockrms', 'fab fa-safari', 'fab fa-sass', 'fab fa-schlix', 'fab fa-scribd', 'fab fa-searchengin',
            'fab fa-sellcast', 'fab fa-sellsy', 'fab fa-servicestack', 'fab fa-shirtsinbulk', 'fab fa-shopware',
            'fab fa-simplybuilt', 'fab fa-sistrix', 'fab fa-sith', 'fab fa-skyatlas', 'fab fa-skype', 'fab fa-slack',
            'fab fa-slack-hash', 'fab fa-slideshare', 'fab fa-snapchat', 'fab fa-snapchat-ghost',
            'fab fa-snapchat-square', 'fab fa-soundcloud', 'fab fa-speakap', 'fab fa-spotify', 'fab fa-squarespace',
            'fab fa-stack-exchange', 'fab fa-stack-overflow', 'fab fa-staylinked', 'fab fa-steam',
            'fab fa-steam-square', 'fab fa-steam-symbol', 'fab fa-sticker-mule', 'fab fa-strava', 'fab fa-stripe',
            'fab fa-stripe-s', 'fab fa-studiovinari', 'fab fa-stumbleupon', 'fab fa-stumbleupon-circle',
            'fab fa-superpowers', 'fab fa-supple', 'fab fa-teamspeak', 'fab fa-telegram', 'fab fa-telegram-plane',
            'fab fa-tencent-weibo', 'fab fa-themeco', 'fab fa-themeisle', 'fab fa-trade-federation', 'fab fa-trello',
            'fab fa-tripadvisor', 'fab fa-tumblr', 'fab fa-tumblr-square', 'fab fa-twitch', 'fab fa-twitter',
            'fab fa-twitter-square', 'fab fa-typo3', 'fab fa-uber', 'fab fa-uikit', 'fab fa-uniregistry',
            'fab fa-untappd', 'fab fa-usb', 'fab fa-ussunnah', 'fab fa-vaadin', 'fab fa-viacoin', 'fab fa-viadeo',
            'fab fa-viadeo-square', 'fab fa-viber', 'fab fa-vimeo', 'fab fa-vimeo-square', 'fab fa-vimeo-v',
            'fab fa-vine', 'fab fa-vk', 'fab fa-vnv', 'fab fa-vuejs', 'fab fa-weebly', 'fab fa-weibo', 'fab fa-weixin',
            'fab fa-whatsapp', 'fab fa-whatsapp-square', 'fab fa-whmcs', 'fab fa-wikipedia-w', 'fab fa-windows',
            'fab fa-wix', 'fab fa-wolf-pack-battalion', 'fab fa-wordpress', 'fab fa-wordpress-simple',
            'fab fa-wpbeginner', 'fab fa-wpexplorer', 'fab fa-wpforms', 'fab fa-xbox', 'fab fa-xing',
            'fab fa-xing-square', 'fab fa-y-combinator', 'fab fa-yahoo', 'fab fa-yandex', 'fab fa-yandex-international',
            'fab fa-yelp', 'fab fa-yoast', 'fab fa-youtube', 'fab fa-youtube-square', 'fab fa-zhihu'
        ];
        let rowDemoIcon = "#row-demo-icon_1";
        for (i = 0; i < iconClass.length; i++) {
            $(rowDemoIcon).append('<div class="col-md-3"> <div class="demo-icon"> <div class="icon-preview"><i class="' +
                iconClass[i] + '"></i></div> <div class="icon-class">' + iconClass[i] + '</div> </div> </div>');
        }


        iconClass = ['icon-user', 'icon-people', 'icon-user-female', 'icon-user-follow', 'icon-user-following',
            'icon-user-unfollow', 'icon-login', 'icon-logout', 'icon-emotsmile', 'icon-phone', 'icon-call-end',
            'icon-call-in', 'icon-call-out', 'icon-map', 'icon-location-pin', 'icon-direction', 'icon-directions',
            'icon-compass', 'icon-layers', 'icon-menu', 'icon-list', 'icon-options-vertical', 'icon-options',
            'icon-arrow-down', 'icon-arrow-left', 'icon-arrow-right', 'icon-arrow-up', 'icon-arrow-up-circle',
            'icon-arrow-left-circle', 'icon-arrow-right-circle', 'icon-arrow-down-circle', 'icon-check', 'icon-clock',
            'icon-plus', 'icon-close', 'icon-trophy', 'icon-screen-smartphone', 'icon-screen-desktop', 'icon-plane',
            'icon-notebook', 'icon-mustache', 'icon-mouse', 'icon-magnet', 'icon-energy', 'icon-disc', 'icon-cursor',
            'icon-cursor-move', 'icon-crop', 'icon-chemistry', 'icon-speedometer', 'icon-shield', 'icon-screen-tablet',
            'icon-magic-wand', 'icon-hourglass', 'icon-graduation', 'icon-ghost', 'icon-game-controller', 'icon-fire',
            'icon-eyeglass', 'icon-envelope-open', 'icon-envelope-letter', 'icon-bell', 'icon-badge', 'icon-anchor',
            'icon-wallet', 'icon-vector', 'icon-speech', 'icon-puzzle', 'icon-printer', 'icon-present', 'icon-playlist',
            'icon-pin', 'icon-picture', 'icon-handbag', 'icon-globe-alt', 'icon-globe', 'icon-folder-alt',
            'icon-folder', 'icon-film', 'icon-feed', 'icon-drop', 'icon-drawer', 'icon-docs', 'icon-doc',
            'icon-diamond', 'icon-cup', 'icon-calculator', 'icon-bubbles', 'icon-briefcase', 'icon-book-open',
            'icon-basket-loaded', 'icon-basket', 'icon-bag', 'icon-action-undo', 'icon-action-redo', 'icon-wrench',
            'icon-umbrella', 'icon-trash', 'icon-tag', 'icon-support', 'icon-frame', 'icon-size-fullscreen',
            'icon-size-actual', 'icon-shuffle', 'icon-share-alt', 'icon-share', 'icon-rocket', 'icon-question',
            'icon-pie-chart', 'icon-pencil', 'icon-note', 'icon-loop', 'icon-home', 'icon-grid', 'icon-graph',
            'icon-microphone', 'icon-music-tone-alt', 'icon-music-tone', 'icon-earphones-alt', 'icon-earphones',
            'icon-equalizer', 'icon-like', 'icon-dislike', 'icon-control-start', 'icon-control-rewind',
            'icon-control-play', 'icon-control-pause', 'icon-control-forward', 'icon-control-end', 'icon-volume-1',
            'icon-volume-2', 'icon-volume-off', 'icon-calendar', 'icon-bulb', 'icon-chart', 'icon-ban', 'icon-bubble',
            'icon-camrecorder', 'icon-camera', 'icon-cloud-download', 'icon-cloud-upload', 'icon-envelope', 'icon-eye',
            'icon-flag', 'icon-heart', 'icon-information', 'icon-key', 'icon-link', 'icon-lock', 'icon-lock-open',
            'icon-magnifier', 'icon-magnifier-add', 'icon-magnifier-remove', 'icon-paper-clip', 'icon-paper-plane',
            'icon-power', 'icon-refresh', 'icon-reload', 'icon-settings', 'icon-star', 'icon-symbol-female',
            'icon-symbol-male', 'icon-target', 'icon-credit-card', 'icon-paypal', 'icon-social-tumblr',
            'icon-social-twitter', 'icon-social-facebook', 'icon-social-instagram', 'icon-social-linkedin',
            'icon-social-pinterest', 'icon-social-github', 'icon-social-gplus', 'icon-social-reddit',
            'icon-social-skype', 'icon-social-dribbble', 'icon-social-behance', 'icon-social-foursqare',
            'icon-social-soundcloud', 'icon-social-spotify', 'icon-social-stumbleupon', 'icon-social-youtube',
            'icon-social-dropbox'
        ];
        rowDemoIcon = "#row-demo-icon_2";
        for (i = 0; i < iconClass.length; i++) {
            $(rowDemoIcon).append('<div class="col-md-3"> <div class="demo-icon"> <div class="icon-preview"><i class="' +
                iconClass[i] + '"></i></div> <div class="icon-class">' + iconClass[i] + '</div> </div> </div>');
        }


        iconClass = [
            'bx bxl-meta',
            'bx bx-lemon',
            'bx bxs-lemon',
            'bx bx-cricket-ball',
            'bx bx-baguette',
            'bx bx-bowl-hot',
            'bx bx-bowl-rice',
            'bx bx-cable-car',
            'bx bx-candles',
            'bx bx-circle-half',
            'bx bx-circle-quarter',
            'bx bx-circle-three-quarter',
            'bx bx-cross',
            'bx bx-fork',
            'bx bx-knife',
            'bx bx-money-withdraw',
            'bx bx-popsicle',
            'bx bx-scatter-chart',
            'bx bxs-baguette',
            'bx bxs-bowl-hot',
            'bx bxs-bowl-rice',
            'bx bxs-cable-car',
            'bx bxs-circle-half',
            'bx bxs-circle-quarter',
            'bx bxs-circle-three-quarter',
            'bx bxs-cricket-ball',
            'bx bxs-invader',
            'bx bx-male-female',
            'bx bxs-popsicle',
            'bx bxs-tree-alt',
            'bx bxl-venmo',
            'bx bxl-upwork',
            'bx bxl-netlify',
            'bx bxl-java',
            'bx bxl-heroku',
            'bx bxl-go-lang',
            'bx bxl-gmail',
            'bx bxl-flask',
            'bx bxl-99designs',
            'bx bxl-500px',
            'bx bxl-adobe',
            'bx bxl-airbnb',
            'bx bxl-algolia',
            'bx bxl-amazon',
            'bx bxl-android',
            'bx bxl-angular',
            'bx bxl-apple',
            'bx bxl-audible',
            'bx bxl-aws',
            'bx bxl-baidu',
            'bx bxl-behance',
            'bx bxl-bing',
            'bx bxl-bitcoin',
            'bx bxl-blender',
            'bx bxl-blogger',
            'bx bxl-bootstrap',
            'bx bxl-chrome',
            'bx bxl-codepen',
            'bx bxl-c-plus-plus',
            'bx bxl-creative-commons',
            'bx bxl-css3',
            'bx bxl-dailymotion',
            'bx bxl-deviantart',
            'bx bxl-dev-to',
            'bx bxl-digg',
            'bx bxl-digitalocean',
            'bx bxl-discord',
            'bx bxl-discord-alt',
            'bx bxl-discourse',
            'bx bxl-django',
            'bx bxl-docker',
            'bx bxl-dribbble',
            'bx bxl-dropbox',
            'bx bxl-drupal',
            'bx bxl-ebay',
            'bx bxl-edge',
            'bx bxl-etsy',
            'bx bxl-facebook',
            'bx bxl-facebook-circle',
            'bx bxl-facebook-square',
            'bx bxl-figma',
            'bx bxl-firebase',
            'bx bxl-firefox',
            'bx bxl-flickr',
            'bx bxl-flickr-square',
            'bx bxl-flutter',
            'bx bxl-foursquare',
            'bx bxl-git',
            'bx bxl-github',
            'bx bxl-gitlab',
            'bx bxl-google',
            'bx bxl-google-cloud',
            'bx bxl-google-plus',
            'bx bxl-google-plus-circle',
            'bx bxl-html5',
            'bx bxl-imdb',
            'bx bxl-instagram',
            'bx bxl-instagram-alt',
            'bx bxl-internet-explorer',
            'bx bxl-invision',
            'bx bxl-javascript',
            'bx bxl-joomla',
            'bx bxl-jquery',
            'bx bxl-jsfiddle',
            'bx bxl-kickstarter',
            'bx bxl-kubernetes',
            'bx bxl-less',
            'bx bxl-linkedin',
            'bx bxl-linkedin-square',
            'bx bxl-magento',
            'bx bxl-mailchimp',
            'bx bxl-markdown',
            'bx bxl-mastercard',
            'bx bxl-mastodon',
            'bx bxl-medium',
            'bx bxl-medium-old',
            'bx bxl-medium-square',
            'bx bxl-messenger',
            'bx bxl-microsoft',
            'bx bxl-microsoft-teams',
            'bx bxl-nodejs',
            'bx bxl-ok-ru',
            'bx bxl-opera',
            'bx bxl-patreon',
            'bx bxl-paypal',
            'bx bxl-periscope',
            'bx bxl-php',
            'bx bxl-pinterest',
            'bx bxl-pinterest-alt',
            'bx bxl-play-store',
            'bx bxl-pocket',
            'bx bxl-product-hunt',
            'bx bxl-python',
            'bx bxl-quora',
            'bx bxl-react',
            'bx bxl-redbubble',
            'bx bxl-reddit',
            'bx bxl-redux',
            'bx bxl-sass',
            'bx bxl-shopify',
            'bx bxl-sketch',
            'bx bxl-skype',
            'bx bxl-slack',
            'bx bxl-slack-old',
            'bx bxl-snapchat',
            'bx bxl-soundcloud',
            'bx bxl-spotify',
            'bx bxl-spring-boot',
            'bx bxl-squarespace',
            'bx bxl-stack-overflow',
            'bx bxl-steam',
            'bx bxl-stripe',
            'bx bxl-tailwind-css',
            'bx bxl-telegram',
            'bx bxl-tiktok',
            'bx bxl-trello',
            'bx bxl-trip-advisor',
            'bx bxl-tumblr',
            'bx bxl-tux',
            'bx bxl-twitch',
            'bx bxl-twitter',
            'bx bxl-unity',
            'bx bxl-unsplash',
            'bx bxl-vimeo',
            'bx bxl-visa',
            'bx bxl-visual-studio',
            'bx bxl-vk',
            'bx bxl-vuejs',
            'bx bxl-whatsapp',
            'bx bxl-whatsapp-square',
            'bx bxl-wikipedia',
            'bx bxl-windows',
            'bx bxl-wix',
            'bx bxl-wordpress',
            'bx bxl-yahoo',
            'bx bxl-yelp',
            'bx bxl-youtube',
            'bx bxl-zoom',
            'bx bx-collapse-alt',
            'bx bx-collapse-horizontal',
            'bx bx-collapse-vertical',
            'bx bx-expand-horizontal',
            'bx bx-expand-vertical',
            'bx bx-injection',
            'bx bx-leaf',
            'bx bx-math',
            'bx bx-party',
            'bx bx-abacus',
            'bx bx-accessibility',
            'bx bx-add-to-queue',
            'bx bx-adjust',
            'bx bx-alarm',
            'bx bx-alarm-add',
            'bx bx-alarm-exclamation',
            'bx bx-alarm-off',
            'bx bx-alarm-snooze',
            'bx bx-album',
            'bx bx-align-justify',
            'bx bx-align-left',
            'bx bx-align-middle',
            'bx bx-align-right',
            'bx bx-analyse',
            'bx bx-anchor',
            'bx bx-angry',
            'bx bx-aperture',
            'bx bx-arch',
            'bx bx-archive',
            'bx bx-archive-in',
            'bx bx-archive-out',
            'bx bx-area',
            'bx bx-arrow-back',
            'bx bx-arrow-from-bottom',
            'bx bx-arrow-from-left',
            'bx bx-arrow-from-right',
            'bx bx-arrow-from-top',
            'bx bx-arrow-to-bottom',
            'bx bx-arrow-to-left',
            'bx bx-arrow-to-right',
            'bx bx-arrow-to-top',
            'bx bx-at',
            'bx bx-atom',
            'bx bx-award',
            'bx bx-badge',
            'bx bx-badge-check',
            'bx bx-ball',
            'bx bx-band-aid',
            'bx bx-bar-chart',
            'bx bx-bar-chart-alt',
            'bx bx-bar-chart-alt-2',
            'bx bx-bar-chart-square',
            'bx bx-barcode',
            'bx bx-barcode-reader',
            'bx bx-baseball',
            'bx bx-basket',
            'bx bx-basketball',
            'bx bx-bath',
            'bx bx-battery',
            'bx bx-bed',
            'bx bx-been-here',
            'bx bx-beer',
            'bx bx-bell',
            'bx bx-bell-minus',
            'bx bx-bell-off',
            'bx bx-bell-plus',
            'bx bx-bible',
            'bx bx-bitcoin',
            'bx bx-blanket',
            'bx bx-block',
            'bx bx-bluetooth',
            'bx bx-body',
            'bx bx-bold',
            'bx bx-bolt-circle',
            'bx bx-bomb',
            'bx bx-bone',
            'bx bx-bong',
            'bx bx-book',
            'bx bx-book-add',
            'bx bx-book-alt',
            'bx bx-book-bookmark',
            'bx bx-book-content',
            'bx bx-book-heart',
            'bx bx-bookmark',
            'bx bx-bookmark-alt',
            'bx bx-bookmark-alt-minus',
            'bx bx-bookmark-alt-plus',
            'bx bx-bookmark-heart',
            'bx bx-bookmark-minus',
            'bx bx-bookmark-plus',
            'bx bx-bookmarks',
            'bx bx-book-open',
            'bx bx-book-reader',
            'bx bx-border-all',
            'bx bx-border-bottom',
            'bx bx-border-inner',
            'bx bx-border-left',
            'bx bx-border-none',
            'bx bx-border-outer',
            'bx bx-border-radius',
            'bx bx-border-right',
            'bx bx-border-top',
            'bx bx-bot',
            'bx bx-bowling-ball',
            'bx bx-box',
            'bx bx-bracket',
            'bx bx-braille',
            'bx bx-brain',
            'bx bx-briefcase',
            'bx bx-briefcase-alt',
            'bx bx-briefcase-alt-2',
            'bx bx-brightness',
            'bx bx-brightness-half',
            'bx bx-broadcast',
            'bx bx-brush',
            'bx bx-brush-alt',
            'bx bx-bug',
            'bx bx-bug-alt',
            'bx bx-building',
            'bx bx-building-house',
            'bx bx-buildings',
            'bx bx-bulb',
            'bx bx-bullseye',
            'bx bx-buoy',
            'bx bx-bus',
            'bx bx-bus-school',
            'bx bx-cabinet',
            'bx bx-cake',
            'bx bx-calculator',
            'bx bx-calendar',
            'bx bx-calendar-alt',
            'bx bx-calendar-check',
            'bx bx-calendar-edit',
            'bx bx-calendar-event',
            'bx bx-calendar-exclamation',
            'bx bx-calendar-heart',
            'bx bx-calendar-minus',
            'bx bx-calendar-plus',
            'bx bx-calendar-star',
            'bx bx-calendar-week',
            'bx bx-calendar-x',
            'bx bx-camera',
            'bx bx-camera-home',
            'bx bx-camera-movie',
            'bx bx-camera-off',
            'bx bx-capsule',
            'bx bx-captions',
            'bx bx-car',
            'bx bx-card',
            'bx bx-caret-down',
            'bx bx-caret-down-circle',
            'bx bx-caret-down-square',
            'bx bx-caret-left',
            'bx bx-caret-left-circle',
            'bx bx-caret-left-square',
            'bx bx-caret-right',
            'bx bx-caret-right-circle',
            'bx bx-caret-right-square',
            'bx bx-caret-up',
            'bx bx-caret-up-circle',
            'bx bx-caret-up-square',
            'bx bx-carousel',
            'bx bx-cart',
            'bx bx-cart-alt',
            'bx bx-cast',
            'bx bx-category',
            'bx bx-category-alt',
            'bx bx-cctv',
            'bx bx-certification',
            'bx bx-chair',
            'bx bx-chalkboard',
            'bx bx-chart',
            'bx bx-chat',
            'bx bx-check',
            'bx bx-checkbox',
            'bx bx-checkbox-checked',
            'bx bx-checkbox-minus',
            'bx bx-checkbox-square',
            'bx bx-check-circle',
            'bx bx-check-double',
            'bx bx-check-shield',
            'bx bx-check-square',
            'bx bx-chevron-down',
            'bx bx-chevron-down-circle',
            'bx bx-chevron-down-square',
            'bx bx-chevron-left',
            'bx bx-chevron-left-circle',
            'bx bx-chevron-left-square',
            'bx bx-chevron-right',
            'bx bx-chevron-right-circle',
            'bx bx-chevron-right-square',
            'bx bx-chevrons-down',
            'bx bx-chevrons-left',
            'bx bx-chevrons-right',
            'bx bx-chevrons-up',
            'bx bx-chevron-up',
            'bx bx-chevron-up-circle',
            'bx bx-chevron-up-square',
            'bx bx-chip',
            'bx bx-church',
            'bx bx-circle',
            'bx bx-clinic',
            'bx bx-clipboard',
            'bx bx-closet',
            'bx bx-cloud',
            'bx bx-cloud-download',
            'bx bx-cloud-drizzle',
            'bx bx-cloud-lightning',
            'bx bx-cloud-light-rain',
            'bx bx-cloud-rain',
            'bx bx-cloud-snow',
            'bx bx-cloud-upload',
            'bx bx-code',
            'bx bx-code-alt',
            'bx bx-code-block',
            'bx bx-code-curly',
            'bx bx-coffee',
            'bx bx-coffee-togo',
            'bx bx-cog',
            'bx bx-coin',
            'bx bx-coin-stack',
            'bx bx-collapse',
            'bx bx-collection',
            'bx bx-color-fill',
            'bx bx-columns',
            'bx bx-command',
            'bx bx-comment',
            'bx bx-comment-add',
            'bx bx-comment-check',
            'bx bx-comment-detail',
            'bx bx-comment-dots',
            'bx bx-comment-edit',
            'bx bx-comment-error',
            'bx bx-comment-minus',
            'bx bx-comment-x',
            'bx bx-compass',
            'bx bx-confused',
            'bx bx-conversation',
            'bx bx-cookie',
            'bx bx-cool',
            'bx bx-copy',
            'bx bx-copy-alt',
            'bx bx-copyright',
            'bx bx-credit-card',
            'bx bx-credit-card-alt',
            'bx bx-credit-card-front',
            'bx bx-crop',
            'bx bx-crosshair',
            'bx bx-crown',
            'bx bx-cube',
            'bx bx-cube-alt',
            'bx bx-cuboid',
            'bx bx-current-location',
            'bx bx-customize',
            'bx bx-cut',
            'bx bx-cycling',
            'bx bx-cylinder',
            'bx bx-data',
            'bx bx-desktop',
            'bx bx-detail',
            'bx bx-devices',
            'bx bx-dialpad',
            'bx bx-dialpad-alt',
            'bx bx-diamond',
            'bx bx-dice-1',
            'bx bx-dice-2',
            'bx bx-dice-3',
            'bx bx-dice-4',
            'bx bx-dice-5',
            'bx bx-dice-6',
            'bx bx-directions',
            'bx bx-disc',
            'bx bx-dish',
            'bx bx-dislike',
            'bx bx-dizzy',
            'bx bx-dna',
            'bx bx-dock-bottom',
            'bx bx-dock-left',
            'bx bx-dock-right',
            'bx bx-dock-top',
            'bx bx-dollar',
            'bx bx-dollar-circle',
            'bx bx-donate-blood',
            'bx bx-donate-heart',
            'bx bx-door-open',
            'bx bx-dots-horizontal',
            'bx bx-dots-horizontal-rounded',
            'bx bx-dots-vertical',
            'bx bx-dots-vertical-rounded',
            'bx bx-doughnut-chart',
            'bx bx-down-arrow',
            'bx bx-down-arrow-alt',
            'bx bx-down-arrow-circle',
            'bx bx-download',
            'bx bx-downvote',
            'bx bx-drink',
            'bx bx-droplet',
            'bx bx-dumbbell',
            'bx bx-duplicate',
            'bx bx-edit',
            'bx bx-edit-alt',
            'bx bx-envelope',
            'bx bx-envelope-open',
            'bx bx-equalizer',
            'bx bx-eraser',
            'bx bx-error',
            'bx bx-error-alt',
            'bx bx-error-circle',
            'bx bx-euro',
            'bx bx-exclude',
            'bx bx-exit',
            'bx bx-exit-fullscreen',
            'bx bx-expand',
            'bx bx-expand-alt',
            'bx bx-export',
            'bx bx-extension',
            'bx bx-face',
            'bx bx-fast-forward',
            'bx bx-fast-forward-circle',
            'bx bx-female',
            'bx bx-female-sign',
            'bx bx-file',
            'bx bx-file-blank',
            'bx bx-file-find',
            'bx bx-film',
            'bx bx-filter',
            'bx bx-filter-alt',
            'bx bx-fingerprint',
            'bx bx-first-aid',
            'bx bx-first-page',
            'bx bx-flag',
            'bx bx-folder',
            'bx bx-folder-minus',
            'bx bx-folder-open',
            'bx bx-folder-plus',
            'bx bx-font',
            'bx bx-font-color',
            'bx bx-font-family',
            'bx bx-font-size',
            'bx bx-food-menu',
            'bx bx-food-tag',
            'bx bx-football',
            'bx bx-fridge',
            'bx bx-fullscreen',
            'bx bx-game',
            'bx bx-gas-pump',
            'bx bx-ghost',
            'bx bx-gift',
            'bx bx-git-branch',
            'bx bx-git-commit',
            'bx bx-git-compare',
            'bx bx-git-merge',
            'bx bx-git-pull-request',
            'bx bx-git-repo-forked',
            'bx bx-glasses',
            'bx bx-glasses-alt',
            'bx bx-globe',
            'bx bx-globe-alt',
            'bx bx-grid',
            'bx bx-grid-alt',
            'bx bx-grid-horizontal',
            'bx bx-grid-small',
            'bx bx-grid-vertical',
            'bx bx-group',
            'bx bx-handicap',
            'bx bx-happy',
            'bx bx-happy-alt',
            'bx bx-happy-beaming',
            'bx bx-happy-heart-eyes',
            'bx bx-hash',
            'bx bx-hdd',
            'bx bx-heading',
            'bx bx-headphone',
            'bx bx-health',
            'bx bx-heart',
            'bx bx-heart-circle',
            'bx bx-heart-square',
            'bx bx-help-circle',
            'bx bx-hide',
            'bx bx-highlight',
            'bx bx-history',
            'bx bx-hive',
            'bx bx-home',
            'bx bx-home-alt',
            'bx bx-home-circle',
            'bx bx-home-heart',
            'bx bx-home-smile',
            'bx bx-horizontal-center',
            'bx bx-hotel',
            'bx bx-hourglass',
            'bx bx-id-card',
            'bx bx-image',
            'bx bx-image-add',
            'bx bx-image-alt',
            'bx bx-images',
            'bx bx-import',
            'bx bx-infinite',
            'bx bx-info-circle',
            'bx bx-info-square',
            'bx bx-intersect',
            'bx bx-italic',
            'bx bx-joystick',
            'bx bx-joystick-alt',
            'bx bx-joystick-button',
            'bx bx-key',
            'bx bx-label',
            'bx bx-landscape',
            'bx bx-laptop',
            'bx bx-last-page',
            'bx bx-laugh',
            'bx bx-layer',
            'bx bx-layer-minus',
            'bx bx-layer-plus',
            'bx bx-layout',
            'bx bx-left-arrow',
            'bx bx-left-arrow-alt',
            'bx bx-left-arrow-circle',
            'bx bx-left-down-arrow-circle',
            'bx bx-left-indent',
            'bx bx-left-top-arrow-circle',
            'bx bx-library',
            'bx bx-like',
            'bx bx-line-chart',
            'bx bx-line-chart-down',
            'bx bx-link',
            'bx bx-link-alt',
            'bx bx-link-external',
            'bx bx-lira',
            'bx bx-list-check',
            'bx bx-list-minus',
            'bx bx-list-ol',
            'bx bx-list-plus',
            'bx bx-list-ul',
            'bx bx-loader',
            'bx bx-loader-alt',
            'bx bx-loader-circle',
            'bx bx-location-plus',
            'bx bx-lock',
            'bx bx-lock-alt',
            'bx bx-lock-open',
            'bx bx-lock-open-alt',
            'bx bx-log-in',
            'bx bx-log-in-circle',
            'bx bx-log-out',
            'bx bx-log-out-circle',
            'bx bx-low-vision',
            'bx bx-magnet',
            'bx bx-mail-send',
            'bx bx-male',
            'bx bx-male-sign',
            'bx bx-map',
            'bx bx-map-alt',
            'bx bx-map-pin',
            'bx bx-mask',
            'bx bx-medal',
            'bx bx-meh',
            'bx bx-meh-alt',
            'bx bx-meh-blank',
            'bx bx-memory-card',
            'bx bx-menu',
            'bx bx-menu-alt-left',
            'bx bx-menu-alt-right',
            'bx bx-merge',
            'bx bx-message',
            'bx bx-message-add',
            'bx bx-message-alt',
            'bx bx-message-alt-add',
            'bx bx-message-alt-check',
            'bx bx-message-alt-detail',
            'bx bx-message-alt-dots',
            'bx bx-message-alt-edit',
            'bx bx-message-alt-error',
            'bx bx-message-alt-minus',
            'bx bx-message-alt-x',
            'bx bx-message-check',
            'bx bx-message-detail',
            'bx bx-message-dots',
            'bx bx-message-edit',
            'bx bx-message-error',
            'bx bx-message-minus',
            'bx bx-message-rounded',
            'bx bx-message-rounded-add',
            'bx bx-message-rounded-check',
            'bx bx-message-rounded-detail',
            'bx bx-message-rounded-dots',
            'bx bx-message-rounded-edit',
            'bx bx-message-rounded-error',
            'bx bx-message-rounded-minus',
            'bx bx-message-rounded-x',
            'bx bx-message-square',
            'bx bx-message-square-add',
            'bx bx-message-square-check',
            'bx bx-message-square-detail',
            'bx bx-message-square-dots',
            'bx bx-message-square-edit',
            'bx bx-message-square-error',
            'bx bx-message-square-minus',
            'bx bx-message-square-x',
            'bx bx-message-x',
            'bx bx-meteor',
            'bx bx-microchip',
            'bx bx-microphone',
            'bx bx-microphone-off',
            'bx bx-minus',
            'bx bx-minus-back',
            'bx bx-minus-circle',
            'bx bx-minus-front',
            'bx bx-mobile',
            'bx bx-mobile-alt',
            'bx bx-mobile-landscape',
            'bx bx-mobile-vibration',
            'bx bx-money',
            'bx bx-moon',
            'bx bx-mouse',
            'bx bx-mouse-alt',
            'bx bx-move',
            'bx bx-move-horizontal',
            'bx bx-move-vertical',
            'bx bx-movie',
            'bx bx-movie-play',
            'bx bx-music',
            'bx bx-navigation',
            'bx bx-network-chart',
            'bx bx-news',
            'bx bx-no-entry',
            'bx bx-note',
            'bx bx-notepad',
            'bx bx-notification',
            'bx bx-notification-off',
            'bx bx-outline',
            'bx bx-package',
            'bx bx-paint',
            'bx bx-paint-roll',
            'bx bx-palette',
            'bx bx-paperclip',
            'bx bx-paper-plane',
            'bx bx-paragraph',
            'bx bx-paste',
            'bx bx-pause',
            'bx bx-pause-circle',
            'bx bx-pen',
            'bx bx-pencil',
            'bx bx-phone',
            'bx bx-phone-call',
            'bx bx-phone-incoming',
            'bx bx-phone-off',
            'bx bx-phone-outgoing',
            'bx bx-photo-album',
            'bx bx-pie-chart',
            'bx bx-pie-chart-alt',
            'bx bx-pie-chart-alt-2',
            'bx bx-pin',
            'bx bx-planet',
            'bx bx-play',
            'bx bx-play-circle',
            'bx bx-plug',
            'bx bx-plus',
            'bx bx-plus-circle',
            'bx bx-plus-medical',
            'bx bx-podcast',
            'bx bx-pointer',
            'bx bx-poll',
            'bx bx-polygon',
            'bx bx-pound',
            'bx bx-power-off',
            'bx bx-printer',
            'bx bx-pulse',
            'bx bx-purchase-tag',
            'bx bx-purchase-tag-alt',
            'bx bx-pyramid',
            'bx bx-qr',
            'bx bx-qr-scan',
            'bx bx-question-mark',
            'bx bx-radar',
            'bx bx-radio',
            'bx bx-radio-circle',
            'bx bx-radio-circle-marked',
            'bx bx-receipt',
            'bx bx-rectangle',
            'bx bx-recycle',
            'bx bx-redo',
            'bx bx-refresh',
            'bx bx-registered',
            'bx bx-rename',
            'bx bx-repeat',
            'bx bx-reply',
            'bx bx-reply-all',
            'bx bx-repost',
            'bx bx-reset',
            'bx bx-restaurant',
            'bx bx-revision',
            'bx bx-rewind',
            'bx bx-rewind-circle',
            'bx bx-right-arrow',
            'bx bx-right-arrow-alt',
            'bx bx-right-arrow-circle',
            'bx bx-right-down-arrow-circle',
            'bx bx-right-indent',
            'bx bx-right-top-arrow-circle',
            'bx bx-rocket',
            'bx bx-rotate-left',
            'bx bx-rotate-right',
            'bx bx-rss',
            'bx bx-ruble',
            'bx bx-ruler',
            'bx bx-run',
            'bx bx-rupee',
            'bx bx-sad',
            'bx bx-save',
            'bx bx-scan',
            'bx bx-screenshot',
            'bx bx-search',
            'bx bx-search-alt',
            'bx bx-search-alt-2',
            'bx bx-selection',
            'bx bx-select-multiple',
            'bx bx-send',
            'bx bx-server',
            'bx bx-shape-circle',
            'bx bx-shape-polygon',
            'bx bx-shape-square',
            'bx bx-shape-triangle',
            'bx bx-share',
            'bx bx-share-alt',
            'bx bx-shekel',
            'bx bx-shield',
            'bx bx-shield-alt',
            'bx bx-shield-alt-2',
            'bx bx-shield-quarter',
            'bx bx-shield-x',
            'bx bx-shocked',
            'bx bx-shopping-bag',
            'bx bx-show',
            'bx bx-show-alt',
            'bx bx-shuffle',
            'bx bx-sidebar',
            'bx bx-sitemap',
            'bx bx-skip-next',
            'bx bx-skip-next-circle',
            'bx bx-skip-previous',
            'bx bx-skip-previous-circle',
            'bx bx-sleepy',
            'bx bx-slider',
            'bx bx-slider-alt',
            'bx bx-slideshow',
            'bx bx-smile',
            'bx bx-sort',
            'bx bx-sort-alt-2',
            'bx bx-sort-a-z',
            'bx bx-sort-down',
            'bx bx-sort-up',
            'bx bx-sort-z-a',
            'bx bx-spa',
            'bx bx-space-bar',
            'bx bx-speaker',
            'bx bx-spray-can',
            'bx bx-spreadsheet',
            'bx bx-square',
            'bx bx-square-rounded',
            'bx bx-star',
            'bx bx-station',
            'bx bx-stats',
            'bx bx-sticker',
            'bx bx-stop',
            'bx bx-stop-circle',
            'bx bx-stopwatch',
            'bx bx-store',
            'bx bx-store-alt',
            'bx bx-street-view',
            'bx bx-strikethrough',
            'bx bx-subdirectory-left',
            'bx bx-subdirectory-right',
            'bx bx-sun',
            'bx bx-support',
            'bx bx-swim',
            'bx bx-sync',
            'bx bx-tab',
            'bx bx-table',
            'bx bx-tachometer',
            'bx bx-tag',
            'bx bx-tag-alt',
            'bx bx-target-lock',
            'bx bx-task',
            'bx bx-task-x',
            'bx bx-taxi',
            'bx bx-tennis-ball',
            'bx bx-terminal',
            'bx bx-test-tube',
            'bx bx-text',
            'bx bx-time',
            'bx bx-time-five',
            'bx bx-timer',
            'bx bx-tired',
            'bx bx-toggle-left',
            'bx bx-toggle-right',
            'bx bx-tone',
            'bx bx-traffic-cone',
            'bx bx-train',
            'bx bx-transfer',
            'bx bx-transfer-alt',
            'bx bx-trash',
            'bx bx-trash-alt',
            'bx bx-trending-down',
            'bx bx-trending-up',
            'bx bx-trim',
            'bx bx-trip',
            'bx bx-trophy',
            'bx bx-tv',
            'bx bx-underline',
            'bx bx-undo',
            'bx bx-unite',
            'bx bx-unlink',
            'bx bx-up-arrow',
            'bx bx-up-arrow-alt',
            'bx bx-up-arrow-circle',
            'bx bx-upload',
            'bx bx-upside-down',
            'bx bx-upvote',
            'bx bx-usb',
            'bx bx-user',
            'bx bx-user-check',
            'bx bx-user-circle',
            'bx bx-user-minus',
            'bx bx-user-pin',
            'bx bx-user-plus',
            'bx bx-user-voice',
            'bx bx-user-x',
            'bx bx-vector',
            'bx bx-vertical-center',
            'bx bx-vial',
            'bx bx-video',
            'bx bx-video-off',
            'bx bx-video-plus',
            'bx bx-video-recording',
            'bx bx-voicemail',
            'bx bx-volume',
            'bx bx-volume-full',
            'bx bx-volume-low',
            'bx bx-volume-mute',
            'bx bx-walk',
            'bx bx-wallet',
            'bx bx-wallet-alt',
            'bx bx-water',
            'bx bx-webcam',
            'bx bx-wifi',
            'bx bx-wifi-0',
            'bx bx-wifi-1',
            'bx bx-wifi-2',
            'bx bx-wifi-off',
            'bx bx-wind',
            'bx bx-window',
            'bx bx-window-alt',
            'bx bx-window-close',
            'bx bx-window-open',
            'bx bx-windows',
            'bx bx-wine',
            'bx bx-wink-smile',
            'bx bx-wink-tongue',
            'bx bx-won',
            'bx bx-world',
            'bx bx-wrench',
            'bx bx-x',
            'bx bx-x-circle',
            'bx bx-yen',
            'bx bx-zoom-in',
            'bx bx-zoom-out',
            'bx bxs-party',
            'bx bxs-hot',
            'bx bxs-droplet',
            'bx bxs-cat',
            'bx bxs-dog',
            'bx bxs-injection',
            'bx bxs-leaf',
            'bx bxs-add-to-queue',
            'bx bxs-adjust',
            'bx bxs-adjust-alt',
            'bx bxs-alarm',
            'bx bxs-alarm-add',
            'bx bxs-alarm-exclamation',
            'bx bxs-alarm-off',
            'bx bxs-alarm-snooze',
            'bx bxs-album',
            'bx bxs-ambulance',
            'bx bxs-analyse',
            'bx bxs-angry',
            'bx bxs-arch',
            'bx bxs-archive',
            'bx bxs-archive-in',
            'bx bxs-archive-out',
            'bx bxs-area',
            'bx bxs-arrow-from-bottom',
            'bx bxs-arrow-from-left',
            'bx bxs-arrow-from-right',
            'bx bxs-arrow-from-top',
            'bx bxs-arrow-to-bottom',
            'bx bxs-arrow-to-left',
            'bx bxs-arrow-to-right',
            'bx bxs-arrow-to-top',
            'bx bxs-award',
            'bx bxs-baby-carriage',
            'bx bxs-backpack',
            'bx bxs-badge',
            'bx bxs-badge-check',
            'bx bxs-badge-dollar',
            'bx bxs-ball',
            'bx bxs-band-aid',
            'bx bxs-bank',
            'bx bxs-bar-chart-alt-2',
            'bx bxs-bar-chart-square',
            'bx bxs-barcode',
            'bx bxs-baseball',
            'bx bxs-basket',
            'bx bxs-basketball',
            'bx bxs-bath',
            'bx bxs-battery',
            'bx bxs-battery-charging',
            'bx bxs-battery-full',
            'bx bxs-battery-low',
            'bx bxs-bed',
            'bx bxs-been-here',
            'bx bxs-beer',
            'bx bxs-bell',
            'bx bxs-bell-minus',
            'bx bxs-bell-off',
            'bx bxs-bell-plus',
            'bx bxs-bell-ring',
            'bx bxs-bible',
            'bx bxs-binoculars',
            'bx bxs-blanket',
            'bx bxs-bolt',
            'bx bxs-bolt-circle',
            'bx bxs-bomb',
            'bx bxs-bone',
            'bx bxs-bong',
            'bx bxs-book',
            'bx bxs-book-add',
            'bx bxs-book-alt',
            'bx bxs-book-bookmark',
            'bx bxs-book-content',
            'bx bxs-book-heart',
            'bx bxs-bookmark',
            'bx bxs-bookmark-alt',
            'bx bxs-bookmark-alt-minus',
            'bx bxs-bookmark-alt-plus',
            'bx bxs-bookmark-heart',
            'bx bxs-bookmark-minus',
            'bx bxs-bookmark-plus',
            'bx bxs-bookmarks',
            'bx bxs-bookmark-star',
            'bx bxs-book-open',
            'bx bxs-book-reader',
            'bx bxs-bot',
            'bx bxs-bowling-ball',
            'bx bxs-box',
            'bx bxs-brain',
            'bx bxs-briefcase',
            'bx bxs-briefcase-alt',
            'bx bxs-briefcase-alt-2',
            'bx bxs-brightness',
            'bx bxs-brightness-half',
            'bx bxs-brush',
            'bx bxs-brush-alt',
            'bx bxs-bug',
            'bx bxs-bug-alt',
            'bx bxs-building',
            'bx bxs-building-house',
            'bx bxs-buildings',
            'bx bxs-bulb',
            'bx bxs-bullseye',
            'bx bxs-buoy',
            'bx bxs-bus',
            'bx bxs-business',
            'bx bxs-bus-school',
            'bx bxs-cabinet',
            'bx bxs-cake',
            'bx bxs-calculator',
            'bx bxs-calendar',
            'bx bxs-calendar-alt',
            'bx bxs-calendar-check',
            'bx bxs-calendar-edit',
            'bx bxs-calendar-event',
            'bx bxs-calendar-exclamation',
            'bx bxs-calendar-heart',
            'bx bxs-calendar-minus',
            'bx bxs-calendar-plus',
            'bx bxs-calendar-star',
            'bx bxs-calendar-week',
            'bx bxs-calendar-x',
            'bx bxs-camera',
            'bx bxs-camera-home',
            'bx bxs-camera-movie',
            'bx bxs-camera-off',
            'bx bxs-camera-plus',
            'bx bxs-capsule',
            'bx bxs-captions',
            'bx bxs-car',
            'bx bxs-car-battery',
            'bx bxs-car-crash',
            'bx bxs-card',
            'bx bxs-caret-down-circle',
            'bx bxs-caret-down-square',
            'bx bxs-caret-left-circle',
            'bx bxs-caret-left-square',
            'bx bxs-caret-right-circle',
            'bx bxs-caret-right-square',
            'bx bxs-caret-up-circle',
            'bx bxs-caret-up-square',
            'bx bxs-car-garage',
            'bx bxs-car-mechanic',
            'bx bxs-carousel',
            'bx bxs-cart',
            'bx bxs-cart-add',
            'bx bxs-cart-alt',
            'bx bxs-cart-download',
            'bx bxs-car-wash',
            'bx bxs-category',
            'bx bxs-category-alt',
            'bx bxs-cctv',
            'bx bxs-certification',
            'bx bxs-chalkboard',
            'bx bxs-chart',
            'bx bxs-chat',
            'bx bxs-checkbox',
            'bx bxs-checkbox-checked',
            'bx bxs-checkbox-minus',
            'bx bxs-check-circle',
            'bx bxs-check-shield',
            'bx bxs-check-square',
            'bx bxs-chess',
            'bx bxs-chevron-down',
            'bx bxs-chevron-down-circle',
            'bx bxs-chevron-down-square',
            'bx bxs-chevron-left',
            'bx bxs-chevron-left-circle',
            'bx bxs-chevron-left-square',
            'bx bxs-chevron-right',
            'bx bxs-chevron-right-circle',
            'bx bxs-chevron-right-square',
            'bx bxs-chevrons-down',
            'bx bxs-chevrons-left',
            'bx bxs-chevrons-right',
            'bx bxs-chevrons-up',
            'bx bxs-chevron-up',
            'bx bxs-chevron-up-circle',
            'bx bxs-chevron-up-square',
            'bx bxs-chip',
            'bx bxs-church',
            'bx bxs-circle',
            'bx bxs-city',
            'bx bxs-clinic',
            'bx bxs-cloud',
            'bx bxs-cloud-download',
            'bx bxs-cloud-lightning',
            'bx bxs-cloud-rain',
            'bx bxs-cloud-upload',
            'bx bxs-coffee',
            'bx bxs-coffee-alt',
            'bx bxs-coffee-togo',
            'bx bxs-cog',
            'bx bxs-coin',
            'bx bxs-coin-stack',
            'bx bxs-collection',
            'bx bxs-color-fill',
            'bx bxs-comment',
            'bx bxs-comment-add',
            'bx bxs-comment-check',
            'bx bxs-comment-detail',
            'bx bxs-comment-dots',
            'bx bxs-comment-edit',
            'bx bxs-comment-error',
            'bx bxs-comment-minus',
            'bx bxs-comment-x',
            'bx bxs-compass',
            'bx bxs-component',
            'bx bxs-confused',
            'bx bxs-contact',
            'bx bxs-conversation',
            'bx bxs-cookie',
            'bx bxs-cool',
            'bx bxs-copy',
            'bx bxs-copy-alt',
            'bx bxs-copyright',
            'bx bxs-coupon',
            'bx bxs-credit-card',
            'bx bxs-credit-card-alt',
            'bx bxs-credit-card-front',
            'bx bxs-crop',
            'bx bxs-crown',
            'bx bxs-cube',
            'bx bxs-cube-alt',
            'bx bxs-cuboid',
            'bx bxs-customize',
            'bx bxs-cylinder',
            'bx bxs-dashboard',
            'bx bxs-data',
            'bx bxs-detail',
            'bx bxs-devices',
            'bx bxs-diamond',
            'bx bxs-dice-1',
            'bx bxs-dice-2',
            'bx bxs-dice-3',
            'bx bxs-dice-4',
            'bx bxs-dice-5',
            'bx bxs-dice-6',
            'bx bxs-direction-left',
            'bx bxs-direction-right',
            'bx bxs-directions',
            'bx bxs-disc',
            'bx bxs-discount',
            'bx bxs-dish',
            'bx bxs-dislike',
            'bx bxs-dizzy',
            'bx bxs-dock-bottom',
            'bx bxs-dock-left',
            'bx bxs-dock-right',
            'bx bxs-dock-top',
            'bx bxs-dollar-circle',
            'bx bxs-donate-blood',
            'bx bxs-donate-heart',
            'bx bxs-door-open',
            'bx bxs-doughnut-chart',
            'bx bxs-down-arrow',
            'bx bxs-down-arrow-alt',
            'bx bxs-down-arrow-circle',
            'bx bxs-down-arrow-square',
            'bx bxs-download',
            'bx bxs-downvote',
            'bx bxs-drink',
            'bx bxs-droplet-half',
            'bx bxs-dryer',
            'bx bxs-duplicate',
            'bx bxs-edit',
            'bx bxs-edit-alt',
            'bx bxs-edit-location',
            'bx bxs-eject',
            'bx bxs-envelope',
            'bx bxs-envelope-open',
            'bx bxs-eraser',
            'bx bxs-error',
            'bx bxs-error-alt',
            'bx bxs-error-circle',
            'bx bxs-ev-station',
            'bx bxs-exit',
            'bx bxs-extension',
            'bx bxs-eyedropper',
            'bx bxs-face',
            'bx bxs-face-mask',
            'bx bxs-factory',
            'bx bxs-fast-forward-circle',
            'bx bxs-file',
            'bx bxs-file-archive',
            'bx bxs-file-blank',
            'bx bxs-file-css',
            'bx bxs-file-doc',
            'bx bxs-file-export',
            'bx bxs-file-find',
            'bx bxs-file-gif',
            'bx bxs-file-html',
            'bx bxs-file-image',
            'bx bxs-file-import',
            'bx bxs-file-jpg',
            'bx bxs-file-js',
            'bx bxs-file-json',
            'bx bxs-file-md',
            'bx bxs-file-pdf',
            'bx bxs-file-plus',
            'bx bxs-file-png',
            'bx bxs-file-txt',
            'bx bxs-film',
            'bx bxs-filter-alt',
            'bx bxs-first-aid',
            'bx bxs-flag',
            'bx bxs-flag-alt',
            'bx bxs-flag-checkered',
            'bx bxs-flame',
            'bx bxs-flask',
            'bx bxs-florist',
            'bx bxs-folder',
            'bx bxs-folder-minus',
            'bx bxs-folder-open',
            'bx bxs-folder-plus',
            'bx bxs-food-menu',
            'bx bxs-fridge',
            'bx bxs-game',
            'bx bxs-gas-pump',
            'bx bxs-ghost',
            'bx bxs-gift',
            'bx bxs-graduation',
            'bx bxs-grid',
            'bx bxs-grid-alt',
            'bx bxs-group',
            'bx bxs-guitar-amp',
            'bx bxs-hand',
            'bx bxs-hand-down',
            'bx bxs-hand-left',
            'bx bxs-hand-right',
            'bx bxs-hand-up',
            'bx bxs-happy',
            'bx bxs-happy-alt',
            'bx bxs-happy-beaming',
            'bx bxs-happy-heart-eyes',
            'bx bxs-hdd',
            'bx bxs-heart',
            'bx bxs-heart-circle',
            'bx bxs-heart-square',
            'bx bxs-help-circle',
            'bx bxs-hide',
            'bx bxs-home',
            'bx bxs-home-circle',
            'bx bxs-home-heart',
            'bx bxs-home-smile',
            'bx bxs-hotel',
            'bx bxs-hourglass',
            'bx bxs-hourglass-bottom',
            'bx bxs-hourglass-top',
            'bx bxs-id-card',
            'bx bxs-image',
            'bx bxs-image-add',
            'bx bxs-image-alt',
            'bx bxs-inbox',
            'bx bxs-info-circle',
            'bx bxs-info-square',
            'bx bxs-institution',
            'bx bxs-joystick',
            'bx bxs-joystick-alt',
            'bx bxs-joystick-button',
            'bx bxs-key',
            'bx bxs-keyboard',
            'bx bxs-label',
            'bx bxs-landmark',
            'bx bxs-landscape',
            'bx bxs-laugh',
            'bx bxs-layer',
            'bx bxs-layer-minus',
            'bx bxs-layer-plus',
            'bx bxs-layout',
            'bx bxs-left-arrow',
            'bx bxs-left-arrow-alt',
            'bx bxs-left-arrow-circle',
            'bx bxs-left-arrow-square',
            'bx bxs-left-down-arrow-circle',
            'bx bxs-left-top-arrow-circle',
            'bx bxs-like',
            'bx bxs-location-plus',
            'bx bxs-lock',
            'bx bxs-lock-alt',
            'bx bxs-lock-open',
            'bx bxs-lock-open-alt',
            'bx bxs-log-in',
            'bx bxs-log-in-circle',
            'bx bxs-log-out',
            'bx bxs-log-out-circle',
            'bx bxs-low-vision',
            'bx bxs-magic-wand',
            'bx bxs-magnet',
            'bx bxs-map',
            'bx bxs-map-alt',
            'bx bxs-map-pin',
            'bx bxs-mask',
            'bx bxs-medal',
            'bx bxs-megaphone',
            'bx bxs-meh',
            'bx bxs-meh-alt',
            'bx bxs-meh-blank',
            'bx bxs-memory-card',
            'bx bxs-message',
            'bx bxs-message-add',
            'bx bxs-message-alt',
            'bx bxs-message-alt-add',
            'bx bxs-message-alt-check',
            'bx bxs-message-alt-detail',
            'bx bxs-message-alt-dots',
            'bx bxs-message-alt-edit',
            'bx bxs-message-alt-error',
            'bx bxs-message-alt-minus',
            'bx bxs-message-alt-x',
            'bx bxs-message-check',
            'bx bxs-message-detail',
            'bx bxs-message-dots',
            'bx bxs-message-edit',
            'bx bxs-message-error',
            'bx bxs-message-minus',
            'bx bxs-message-rounded',
            'bx bxs-message-rounded-add',
            'bx bxs-message-rounded-check',
            'bx bxs-message-rounded-detail',
            'bx bxs-message-rounded-dots',
            'bx bxs-message-rounded-edit',
            'bx bxs-message-rounded-error',
            'bx bxs-message-rounded-minus',
            'bx bxs-message-rounded-x',
            'bx bxs-message-square',
            'bx bxs-message-square-add',
            'bx bxs-message-square-check',
            'bx bxs-message-square-detail',
            'bx bxs-message-square-dots',
            'bx bxs-message-square-edit',
            'bx bxs-message-square-error',
            'bx bxs-message-square-minus',
            'bx bxs-message-square-x',
            'bx bxs-message-x',
            'bx bxs-meteor',
            'bx bxs-microchip',
            'bx bxs-microphone',
            'bx bxs-microphone-alt',
            'bx bxs-microphone-off',
            'bx bxs-minus-circle',
            'bx bxs-minus-square',
            'bx bxs-mobile',
            'bx bxs-mobile-vibration',
            'bx bxs-moon',
            'bx bxs-mouse',
            'bx bxs-mouse-alt',
            'bx bxs-movie',
            'bx bxs-movie-play',
            'bx bxs-music',
            'bx bxs-navigation',
            'bx bxs-network-chart',
            'bx bxs-news',
            'bx bxs-no-entry',
            'bx bxs-note',
            'bx bxs-notepad',
            'bx bxs-notification',
            'bx bxs-notification-off',
            'bx bxs-offer',
            'bx bxs-package',
            'bx bxs-paint',
            'bx bxs-paint-roll',
            'bx bxs-palette',
            'bx bxs-paper-plane',
            'bx bxs-parking',
            'bx bxs-paste',
            'bx bxs-pen',
            'bx bxs-pencil',
            'bx bxs-phone',
            'bx bxs-phone-call',
            'bx bxs-phone-incoming',
            'bx bxs-phone-off',
            'bx bxs-phone-outgoing',
            'bx bxs-photo-album',
            'bx bxs-piano',
            'bx bxs-pie-chart',
            'bx bxs-pie-chart-alt',
            'bx bxs-pie-chart-alt-2',
            'bx bxs-pin',
            'bx bxs-pizza',
            'bx bxs-plane',
            'bx bxs-plane-alt',
            'bx bxs-plane-land',
            'bx bxs-planet',
            'bx bxs-plane-take-off',
            'bx bxs-playlist',
            'bx bxs-plug',
            'bx bxs-plus-circle',
            'bx bxs-plus-square',
            'bx bxs-pointer',
            'bx bxs-polygon',
            'bx bxs-printer',
            'bx bxs-purchase-tag',
            'bx bxs-purchase-tag-alt',
            'bx bxs-pyramid',
            'bx bxs-quote-alt-left',
            'bx bxs-quote-alt-right',
            'bx bxs-quote-left',
            'bx bxs-quote-right',
            'bx bxs-quote-single-left',
            'bx bxs-quote-single-right',
            'bx bxs-radiation',
            'bx bxs-radio',
            'bx bxs-receipt',
            'bx bxs-rectangle',
            'bx bxs-registered',
            'bx bxs-rename',
            'bx bxs-report',
            'bx bxs-rewind-circle',
            'bx bxs-right-arrow',
            'bx bxs-right-arrow-alt',
            'bx bxs-right-arrow-circle',
            'bx bxs-right-arrow-square',
            'bx bxs-right-down-arrow-circle',
            'bx bxs-right-top-arrow-circle',
            'bx bxs-rocket',
            'bx bxs-ruler',
            'bx bxs-sad',
            'bx bxs-save',
            'bx bxs-school',
            'bx bxs-search',
            'bx bxs-search-alt-2',
            'bx bxs-select-multiple',
            'bx bxs-send',
            'bx bxs-server',
            'bx bxs-shapes',
            'bx bxs-share',
            'bx bxs-share-alt',
            'bx bxs-shield',
            'bx bxs-shield-alt-2',
            'bx bxs-shield-x',
            'bx bxs-ship',
            'bx bxs-shocked',
            'bx bxs-shopping-bag',
            'bx bxs-shopping-bag-alt',
            'bx bxs-shopping-bags',
            'bx bxs-show',
            'bx bxs-skip-next-circle',
            'bx bxs-skip-previous-circle',
            'bx bxs-skull',
            'bx bxs-sleepy',
            'bx bxs-slideshow',
            'bx bxs-smile',
            'bx bxs-sort-alt',
            'bx bxs-spa',
            'bx bxs-speaker',
            'bx bxs-spray-can',
            'bx bxs-spreadsheet',
            'bx bxs-square',
            'bx bxs-square-rounded',
            'bx bxs-star',
            'bx bxs-star-half',
            'bx bxs-sticker',
            'bx bxs-stopwatch',
            'bx bxs-store',
            'bx bxs-store-alt',
            'bx bxs-sun',
            'bx bxs-tachometer',
            'bx bxs-tag',
            'bx bxs-tag-alt',
            'bx bxs-tag-x',
            'bx bxs-taxi',
            'bx bxs-tennis-ball',
            'bx bxs-terminal',
            'bx bxs-thermometer',
            'bx bxs-time',
            'bx bxs-time-five',
            'bx bxs-timer',
            'bx bxs-tired',
            'bx bxs-toggle-left',
            'bx bxs-toggle-right',
            'bx bxs-tone',
            'bx bxs-torch',
            'bx bxs-to-top',
            'bx bxs-traffic',
            'bx bxs-traffic-barrier',
            'bx bxs-traffic-cone',
            'bx bxs-train',
            'bx bxs-trash',
            'bx bxs-trash-alt',
            'bx bxs-tree',
            'bx bxs-trophy',
            'bx bxs-truck',
            'bx bxs-t-shirt',
            'bx bxs-tv',
            'bx bxs-up-arrow',
            'bx bxs-up-arrow-alt',
            'bx bxs-up-arrow-circle',
            'bx bxs-up-arrow-square',
            'bx bxs-upside-down',
            'bx bxs-upvote',
            'bx bxs-user',
            'bx bxs-user-account',
            'bx bxs-user-badge',
            'bx bxs-user-check',
            'bx bxs-user-circle',
            'bx bxs-user-detail',
            'bx bxs-user-minus',
            'bx bxs-user-pin',
            'bx bxs-user-plus',
            'bx bxs-user-rectangle',
            'bx bxs-user-voice',
            'bx bxs-user-x',
            'bx bxs-vector',
            'bx bxs-vial',
            'bx bxs-video',
            'bx bxs-video-off',
            'bx bxs-video-plus',
            'bx bxs-video-recording',
            'bx bxs-videos',
            'bx bxs-virus',
            'bx bxs-virus-block',
            'bx bxs-volume',
            'bx bxs-volume-full',
            'bx bxs-volume-low',
            'bx bxs-volume-mute',
            'bx bxs-wallet',
            'bx bxs-wallet-alt',
            'bx bxs-washer',
            'bx bxs-watch',
            'bx bxs-watch-alt',
            'bx bxs-webcam',
            'bx bxs-widget',
            'bx bxs-window-alt',
            'bx bxs-wine',
            'bx bxs-wink-smile',
            'bx bxs-wink-tongue',
            'bx bxs-wrench',
            'bx bxs-x-circle',
            'bx bxs-x-square',
            'bx bxs-yin-yang',
            'bx bxs-zap',
            'bx bxs-zoom-in',
            'bx bxs-zoom-out',
        ];
        rowDemoIcon = "#row-demo-icon_3";
        for (i = 0; i < iconClass.length; i++) {
            $(rowDemoIcon).append('<div class="col-md-3"> <div class="demo-icon"> <div class="icon-preview"><i class="' +
                iconClass[i] + '"></i></div> <div class="icon-class">' + iconClass[i] + '</div> </div> </div>');
        }
    </script>
@endsection
